### ISSUE TITLE
Can I use this in production yet?

### ISSUE THREAD

**Issue by mohammed-workfellow** [sethmlarson/truststore#103]
First: Awesome work. Certificate issue in enterprise is the main cause of at least 10% of my grey hair.
Second: I watched your talk from 2022 and read the documentation and release log and still not fully confident. Is this ready for production now? Can I already import this magic and have it fix my problem?

**Comment by davisagli** [comment]
@mohammed-workfellow We are not aware of any reason that it is not ready for production. But, the software is offered without any guarantee, and there is no way we can be aware of the specific certificate validation requirements of every environment where it might be deployed. It is your responsibility to try it and make sure it does what is needed and expected for your specific use case.

If you find a specific problem, please open a new issue.
