### ISSUE TITLE
Truststore not fetching missing certs in AWS ECS linux OS

### ISSUE THREAD

**Issue by AgrPriyank** [sethmlarson/truststore#118]
Hi Guys,

I tested my service with truststore library in MacOS to fetch missing certs and it is working fine. However, when the service is deployed to AWS ECS with linux OS, it doesn't seem to work and still throws SSL CERT VERIFY FAILED error. 
Do you know if there's other setting I need to enable?

**Comment by sethmlarson** [comment]
On Linux the Truststore library uses OpenSSL which doesn't have the ability to automatically fetch intermediates unfortunately. On that platform you'll need to load the intermediates into the store on the system or have them sent in during the handshake.
