### ISSUE TITLE
Python 3.13 support

### ISSUE THREAD

**Issue by layday** [sethmlarson/truststore#131]
:wave: 3.13 is still in alpha, but I thought I'd file this - in https://github.com/python/cpython/pull/109113, `get_unverified_chain` was made public and calls `public_bytes` on the certs, meaning that https://github.com/sethmlarson/truststore/blob/178fea29c3fb5b14a62deeb112ed3e3d81e95157/src/truststore/_api.py#L299 throws an error.

**Comment by sethmlarson** [comment]
@layday Thanks for reporting this, we'll update and get a new version published.

**Comment by layday** [comment]
(Typeshed PR: https://github.com/python/typeshed/pull/11724)
