### ISSUE TITLE
why not just use ssl.create_default_context() instead of this package?

### ISSUE THREAD

**Issue by suiluj** [sethmlarson/truststore#144]
hello I am not understanding why this package is needed.

I think the system ssl context can be retrieved via ssl alone?

```python
import ssl
import httpx
context = ssl.create_default_context()

httpx.get('https://example.org', verify=context)
```

Why would I need the truststore package? What is the advantage when I am setting the context for a request like this?

**Comment by sethmlarson** [comment]
We've [documented the benefits](https://truststore.readthedocs.io/en/latest/#truststore) of using operating system APIs for trust stores over a static list of certificates (the default `SSLContext` behavior). The biggest benefit for users is that Python and pip "just work" the same as their browsers and other programs in an environment with a corporate proxy and custom certificates without requiring any hacking or disabling of security features.

**Comment by sethmlarson** [comment]
(Closing this issue as answered, feel free to continue asking questions).
