### ISSUE TITLE
Is it necessary for truststore to do its own hostname matching?

### ISSUE THREAD

**Issue by davisagli** [sethmlarson/truststore#21]
Currently on all 3 platforms, truststore is setting `TrustStoreSSLContext.check_hostname` to False to suppress the built-in hostname check, and then doing its own check at the bottom of `_verify_peercerts`

On Mac, this isn't necessary because the hostname is passed to Security.SecPolicyCreateSSL -- the tests still pass if I comment out the call to `_match_hostname`. On Windows the situation is similar with the hostname passed to CertVerifyCertificateChainPolicy.

On Linux I think we _should_ be able to set `check_hostname = True` and rely on the built-in check, since verify_mode is not set to None. But, in fact this fails the test with urllib3 when the hostname is an IP address because urllib3 is not passing the hostname along to `wrap_socket` in that case.

So the question is a) am I missing something, and b) can we get rid of _match_hostname?

(And one more minor question: is there any problem that _verify_peercerts is using sslobj.get_verified_chain() to get the hostname, given that the ssl module doesn't know how to verify the chain on its own?)

**Comment by sethmlarson** [comment]
@davisagli Thanks for raising this. There's a good chance that I couldn't get hostname checking to work on macOS (likely had a setting wrong as you said) and couldn't figure out why so decided to lift CPython's. But if we can get it working natively I'm all for it!

From reading the docs on the underlying OpenSSL calls: `get_verified_chain` is the same as `get_unverified_chain` if the verification wasn't successful so I think we should switch to `get_unverified_chain` to be explicit :+1:

**Comment by davisagli** [comment]
> But, in fact this fails the test with urllib3 when the hostname is an IP address because urllib3 is not passing the hostname along to wrap_socket in that case.

It looks like this was already fixed in the main branch of urllib3: https://github.com/urllib3/urllib3/pull/2176
