### ISSUE TITLE
Double CI jobs

### ISSUE THREAD

**Issue by davisagli** [sethmlarson/truststore#25]
I'd suggest picking either the `push` or `pull_request` events to trigger CI (and be required for merge), instead of both, depending on whether you want it to run for branches without a PR or not. As it is we end up with:

![Screen Shot 2022-03-28 at 12 32 47 AM](https://user-images.githubusercontent.com/49014/160327131-932ca318-56b7-49e4-a1f0-86cff3891693.png)

**Comment by sethmlarson** [comment]
Definitely agree, let's use `pull_request` and only run `push` on the `main` branch?
