### ISSUE TITLE
Linux/BSD system trust

### ISSUE THREAD

**Issue by tiran** [sethmlarson/truststore#32]
I suggest that you reconsider the load order for system trust store on Linux and BSD. OpenSSL prefers ``SSL_CERT_FILE`` / ``SSL_CERT_DIR`` env vars and then falls back to compile-time locations for cafile and capath. If you deviate from the default, then it may not only break applications that rely on the order. Linux vendors will patch and modify your code to re-establish default settings, too. You can get the defaults from Python's ssl module:

```
>>> ssl.get_default_verify_paths()
DefaultVerifyPaths(cafile='/etc/pki/tls/cert.pem', capath='/etc/pki/tls/certs', openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/etc/pki/tls/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/etc/pki/tls/certs')
```

The ``cafile`` and ``capath`` attributes resolve the env vars.

For cafile, do

1) check for ``SSL_CERT_FILE``, use it if the env var is set and don't search for additional locations. An empty or invalid ``SSL_CERT_FILE`` is
2) check the hard-coded value from OpenSSL, stop if the file exists (even when it is empty)
3) search common default paths

For capath, do

1) check for ``SSL_CERT_DIR``
2) check the hard-coded value from OpenSSL is a valid directory with at least one file matching ``r"[0-9a-fA-F]{8}\.[0-9]"``
3) search common default directories

You may even want to be more strict. If either ``SSL_CERT_FILE`` is set, ``SSL_CERT_DIR`` is set, default cafile exists, or default capath contains certs, then call ``load_default_certs()`` or ``set_default_verify_paths()``. Only fall back to alternative search paths if the defaults don't work.

I also noticed that you are using an old, outdated list of cert file locations. I have seen the list before in other projects. It contains wrong paths (FreeBSD) or discontinued distros (OpenELEC). You can find an up to date list of paths for Linux at https://github.com/tiran/certifi-system-store/blob/main/src/certifi/core.py and some research at https://github.com/tiran/distro-truststore/.

**Comment by sethmlarson** [comment]
Thanks for making me aware of the right order to do things @tiran!

**Comment by tiran** [comment]
On systems with a capath (Debian) you also may want to skip the cafile. The purpose of capath is to load certs on demand. If you load the cafile, then you don't need capath. Both *should* contain the same set of certificates.

**Comment by sethmlarson** [comment]
@tiran We've started implementing "additional trust anchors" support and I wasn't immediately aware of the best way to handle `capath`. `cafile` and `cadata` are much easier as data is loaded on demand via `load_verify_locations`.

Looked at some of the Windows and macOS APIs and didn't see a way to specify a directory to use for verifying the certificates, should we be loading all the certificates on `load_verify_locations()` immediately or?

**Comment by davisagli** [comment]
Thanks @tiran, this all looks like really helpful and hard-won advice.

We can probably look this up, but I'm curious how the on-demand loading from `capath` works. i.e. when and how does OpenSSL decide which file(s) to load from there?

**Comment by tiran** [comment]
> We can probably look this up, but I'm curious how the on-demand loading from `capath` works. i.e. when and how does OpenSSL decide which file(s) to load from there?

A capath directory contains symlinks from hash file names to the actual certificate. The hash file name is defined by the truncated hash of the cert subject. When OpenSSL encounters a missing issuer certificate in a chain, it hashes the issuer name of the last known cert in the chain. It then uses the hash to find a matching certificate in the capath directory.

**Comment by tiran** [comment]
man page: https://www.openssl.org/docs/man1.1.1/man1/c_rehash.html

You could take Go's approach and just load all files from the directory: https://github.com/golang/go/blob/go1.18/src/crypto/x509/root_unix.go#L61
