### ISSUE TITLE
Add automated publishing to PyPI

### ISSUE THREAD

**Issue by davisagli** [sethmlarson/truststore#46]
Maybe a manually triggered github workflow with required review? https://docs.github.com/en/actions/managing-workflow-runs/reviewing-deployments

**Comment by sethmlarson** [comment]
Probably done in https://github.com/sethmlarson/truststore/pull/52, once we get a successful deploy I'll close this issue.

**Comment by sethmlarson** [comment]
Since the release in https://github.com/sethmlarson/truststore/pull/55 worked perfectly I'm going to close this issue.
