### ISSUE TITLE
Did truststore work correctly for your operating system?

### ISSUE THREAD

**Issue by sethmlarson** [sethmlarson/truststore#63]
If you're here from the article and running pip with `--use-feature=truststore` worked on your machine then leave a reaction below based on your operating system. **To avoid spam, please do not comment unless your operating system isn't represented below.**

- :+1: (Windows)
- :smile: (macOS 10.x or earlier)
- :rocket: (macOS 11 or later)
- :eyes: (Linux flavors like Ubuntu, Debian, Mint, CentOS, RedHat, Fedora, or similar derivatives)
- :heart: (*BSD)
- :tada: (Any Linux that uses LibreSSL)

If your operating system isn't represented in this list then you can comment below.

If truststore didn't work then please open an issue describing your environment and operating system.

**Comment by joshuadavidthomas** [comment]
How would you prefer people running a Linux flavor from within WSL in Windows to vote?

**Comment by sethmlarson** [comment]
@joshuadavidthomas I think Linux, because OpenSSL is the trust store type in that case. Thanks for testing!

**Comment by sethmlarson** [comment]
Thanks everyone who reported their experience, going to close this issue as it's been open for some time now.
