### ISSUE TITLE
Please package testsuite to the distribution tarball

### ISSUE THREAD

**Issue by mcepl** [sethmlarson/truststore#65]
I would like to fix packaging for OpenSUSE, but your [release tarball](https://github.com/sethmlarson/truststore/releases/download/v0.4.0/truststore-0.4.0.tar.gz) does not contain the tests directory. Could you please distribute them as well?

**Comment by sethmlarson** [comment]
I'm going to decline adding the test suite to our source distribution as I think it's abusing the "anything goes" nature of the source distribution format. We'd then have to include `dev-requirements.txt`, `noxfile.py`, and any other config files that come with our test suite.

Is it okay instead to test repackaged code using the test suite at a given git tag from this repository? Then you can use `nox` and benefit from any changes we make locally automatically.

**Comment by mcepl** [comment]
OK, using the tarball from GitHub, but I had to skip tests requiring network (openSUSE as every other distributor isolates their build systems from network for obvious reasons) with this [patch](https://github.com/sethmlarson/truststore/files/9218554/no-network-testing.patch.txt), but the result is rather abysmal:
```
[    5s] + PYTHONPATH=/home/abuild/rpmbuild/BUILDROOT/python-truststore-0.4.0-0.x86_64/usr/lib/python3.10/site-packages
[    5s] + PYTHONDONTWRITEBYTECODE=1
[    5s] + pytest-3.10 --ignore=_build. --ignore=_build.python310 -v -k 'not network'
[    5s] ============================= test session starts ==============================
[    5s] platform linux -- Python 3.10.5, pytest-7.1.1, pluggy-1.0.0 -- /usr/bin/python3.10
[    5s] cachedir: .pytest_cache
[    5s] rootdir: /home/abuild/rpmbuild/BUILD/truststore-0.4.0, configfile: pyproject.toml
[    5s] plugins: asyncio-0.18.3, httpserver-1.0.2
[    5s] asyncio: mode=strict
[    5s] collecting ... collected 9 items / 7 deselected / 2 selected
[    5s] 
[    5s] test_truststore.py::test_trustme_cert PASSED                             [ 50%]
[    6s] test_truststore.py::test_trustme_cert_loaded_via_capath PASSED           [100%]
[    6s] 
[    6s] ======================= 2 passed, 7 deselected in 0.76s ========================
```

Probably better than nothing. I hope.

**Comment by sethmlarson** [comment]
Yeah, unfortunately many of our test cases depend on specifically configured certificates from badssl.com. Maybe we can remedy this in the future by using trustme to create these situations but some are even tough still like revoked or "known-bad" certificates.

For now though, we do test every commit so in theory as long as functionality isn't modified downstream that should be all good.

Are we okay to close this issue then?

**Comment by mcepl** [comment]
I think so, thank you.
