### ISSUE TITLE
❓ Use truststore with requests library

### ISSUE THREAD

**Issue by guerda** [sethmlarson/truststore#71]
[Requests ](https://requests.readthedocs.io/en/latest/user/quickstart/) is quite a popular library for http requests. It uses urllib3 as the powerhouse and it would be great if I could use truststore also with requests.
I am not sure if this something for requests to implement or needs instruction here.

I have not found a direct injection point where can I access the SSL context in urllib3 from a requests `Session` .

Would it be possible to use truststore with requests somehow?

**Comment by sethmlarson** [comment]
Great question! We documented using `truststore.SSLContext` with Requests here: https://truststore.readthedocs.io/en/latest/#using-truststore-with-requests

Going to close this as answered, thanks for giving Truststore a try! :)

**Comment by guerda** [comment]
Thanks, Seth, this is awesome (and you are blazingly fast in answering). Maybe it's helpful to add a hint in the README?

In my case, I experience some errors with using it with requests and with urllib3. Not sure if this is the right place to document

```
urllib3\connection.py:458: SubjectAltNameWarning: Certificate for xxx.intranet.cnb has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/urllib3/urllib3/issues/497 for details.)
  warnings.warn(
ERROR empty or no certificate, match_hostname needs a SSL socket or SSL context with either CERT_OPTIONAL or CERT_REQUIRED
```



```
>>> import urllib3
>>> import truststore
>>> ctx = truststore.SSLContext()
<stdin>:1: DeprecationWarning: ssl.SSLContext() without protocol argument is deprecated.
<stdin>:1: DeprecationWarning: ssl.PROTOCOL_TLS is deprecated
>>> http = urllib3.PoolManager(ssl_context=ctx)
>>> resp = http.request('GET', 'https://xxx.intranet.cnb')
C:\Users\wdwni\.virtualenvs\sdr-api-example-WgBfLP6C\lib\site-packages\urllib3\connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'xxx.intranet.cnb'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
>>> resp = http.request('GET', 'https://yyy.intranet.cnb')
C:\Users\wdwni\.virtualenvs\sdr-api-example-WgBfLP6C\lib\site-packages\urllib3\connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'yyy.intranet.cnb'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
>>> truststore.__version__
'0.4.0'
>>> urllib3.__version__
'1.26.11'
```

**Comment by sethmlarson** [comment]
Oh haha, I didn't realize this was closed within 2 minutes. You just got lucky on hitting my usual morning GitHub notifications scan ;)

That issue is interesting, could you open a separate issue with this information so we can track it? We may need to augment our existing test suite to ensure no DeprecationWarnings are emitted.

**Comment by davisagli** [comment]
The test suite already checks for no warnings, but the requests example in the docs needs to be updated to specify PROTOCOL_TLS_CLIENT

**Comment by sethmlarson** [comment]
Ah you're right @davisagli, nice catch. Hmm, maybe we should provide a "create_default_context()" function too? 🤔

**Comment by davisagli** [comment]
@sethmlarson I'm open to that, but I'm not sure it adds much over just teaching people to use the existing SSLContext API correctly.

**Comment by davisagli** [comment]
@sethmlarson Now that I re-read the docs for `create_default_context`, it makes a bit more sense since it defaults to purpose=Purpose.SERVER_AUTH and sets some other things in addition to the protocol. I wish there was a way for us to wrap `create_default_context` from the stdlib but provide our own SSLContext class. Without a way to do that it seems like it'll be tricky to add a version to truststore while making sure it always applies the same defaults as `ssl.create_default_context` (modulo the trust authorities of course)

**Comment by davisagli** [comment]
We could copy `create_default_context` a la https://stackoverflow.com/questions/13503079/how-to-create-a-copy-of-a-python-function but reassign its `__globals__`, but is that too devious?

**Comment by guerda** [comment]
Thanks for the replies, I'm okay with opening a new issue, but I was not able to follow your analysis, so not really sure what the issue now is concretely 🙈
Anyways: I opened it here: #72
