### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate

### ISSUE THREAD

**Issue by pilgrimage80** [sethmlarson/truststore#84]
Hello, could the source of this problem be that the python system does not use the certification repository? I am very new to this topic, I may be asking a silly question. Actually what I want to do is to login users to the 2nd website using GitLab as an OAuth between two websites but I get the following error. I created a certificate in Gitlab. I have Python 3.8 and pip 19.3 in my environment. How can I solve this problem?

thankyou for support.

An error occurred while attempting to login via your social network account.

HTTPSConnectionPool(host='gitlab.tutel', port=443): Max retries exceeded with url: /oauth/token
(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:
self-signed certificate (_ssl.c:997)')))

**Comment by sethmlarson** [comment]
Are you using truststore anywhere in your codebase? If not then it's unlikely that truststore is your issue. This is likely then an actual certificate issue.

**Comment by sethmlarson** [comment]
Going to close this issue until we hear more about your use-case, hopefully the above comment helped?
